experiment_name: 'semantic_cityscapes'

model:
    type: 'guda'

    encoder:
        params:
            nof_layers: 50
            weights_init: 'pretrained'

    pose_net:
        input: 'pairs' # 'all'
        params:
            nof_layers: 18
            weights_init: 'pretrained'

datasets:
    paths_to_configs : ['/home/bauschb/Masterthesis/Depth-Semantic-UDA/cfg/yaml_files_server/train/semantic/train_on_cityscapes/cityscapes_semantic.yaml',
                        '/home/bauschb/Masterthesis/Depth-Semantic-UDA/cfg/yaml_files_server/train/semantic/train_on_cityscapes/cityscapes_semantic_val.yaml']
    loss_weights : [1, 0]

train:
    nof_epochs: 40
    batch_size: 1

    optimizer:
        type: 'Adam'
        learning_rate: 0.0001
    scheduler:
        type: 'MultiStepLR'
        gamma: 0.5
        milestones: [30] # half the learning rate for the last 10 epochs

val:
    batch_size: 1
    nof_workers: 4

checkpoint:
    use_checkpoint: False

device:
    multiple_gpus: True

io:
    path_save: '/work/dlclarge1/bauschb-data/models/semantic_trained_on_cityscapes'
