model:
    type: 'monodepth2'
    depth_net:
        params:
            nof_layers: 18
            weights_init: 'pretrained'

    pose_net:
        input: 'pairs' # 'all'

train:
    nof_epochs: 20
    batch_size: 4
    rgb_frame_offsets: [0, -1, +1]

    optimizer:
        type: 'Adam'
        learning_rate: 0.0001
    scheduler:
        type: 'StepLR'
        step_size: 10
        gamma: 0.1

dataset:
    name: 'kalimu'
    path: '/home/petek/kalimu/data/kalimu/base'
    feed_img_size: [608, 512]
    use_sparse_depth: True
    camera: 'pinhole'

losses:
    reconstruction:
        nof_scales: 4
        use_ssim: True
        use_automasking: True

    weights:
        reconstruction: 1.0
        # depth weight is set to 1 per definition as the relative weighting ir relevant only

eval:
    train:
        gt_available: False
    val:
        gt_available: False
    test:
        gt_available: False
