experiment_name: 'testing_guda_update_tscl_motion'

model:
    type: 'guda'
    create_expo_moving_avg_model_copy: True

    encoder:
        params:
            nof_layers: 101
            weights_init: 'pretrained'

    pose_net:
        input: 'pairs' # 'all'
        params:
            nof_layers: 18
            weights_init: 'pretrained'
            predict_motion_map: True

datasets:
    paths_to_configs : ['C:\Users\benba\Documents\University\Masterarbeit\Depth-Semantic-UDA\cfg\yaml_files\train\guda_with_tscl_motion\synthia.yaml', #source
                        'C:\Users\benba\Documents\University\Masterarbeit\Depth-Semantic-UDA\cfg\yaml_files\train\guda_with_tscl_motion\cityscapes_sequence.yaml', # target
                        'C:\Users\benba\Documents\University\Masterarbeit\Depth-Semantic-UDA\cfg\yaml_files\train\guda_with_tscl_motion\cityscapes_semantic.yaml'] # validation dataset
    loss_weights : [1, 1, 0]

train:
    nof_epochs: 40
    batch_size: 1

    optimizer:
        type: 'Adam'
        learning_rate: 0.0001
    scheduler:
        type: 'MultiStepLR'
        gamma: 0.5
        milestones: [30] # half the learning rate for the last 10 epochs

val:
    batch_size: 1
    nof_workers: 4

checkpoint:
    use_checkpoint: False
    path_base: 'D:\Depth-Semantic-UDA\experiments\guda'
    filename: 'checkpoint_epoch_0.pth'

device:
    multiple_gpus: False

io:
    path_save: 'D:\Depth-Semantic-UDA\experiments\todelete'
