experiment_name: 'synthia_to_cityscapes'

model:
    type: 'deeplabv3'

    encoder:
        params:
            nof_layers: 101
            weights_init: 'pretrained'

    pose_net:
        input: 'pairs'
        params:
            nof_layers: 18
            weights_init: 'pretrained'

datasets:
    paths_to_configs : ['/home/bauschb/Masterthesis/Depth-Semantic-UDA/cfg/yaml_files_server/train/deeplab_guda/synthia.yaml', #source
                        '/home/bauschb/Masterthesis/Depth-Semantic-UDA/cfg/yaml_files_server/train/deeplab_guda/cityscapes_sequence.yaml', # target
                        '/home/bauschb/Masterthesis/Depth-Semantic-UDA/cfg/yaml_files_server/train/deeplab_guda/cityscapes_semantic.yaml'] # validation dataset
    loss_weights : [1, 1, 0]

train:
    nof_epochs: 120
    batch_size: 1
    nof_workers: 5

    optimizer:
        type: 'Adam'
        learning_rate: 0.0001
    scheduler:
        type: 'MultiStepLR'
        gamma: 0.5
        milestones: [200] # half the learning rate for the last 10 epochs

val:
    batch_size: 1
    nof_workers: 5


device:
    multiple_gpus: True

io:
    path_save: '/work/dlclarge1/bauschb-data/models/deeplabv3_synthia_to_cityscapes'

checkpoint:
    use_checkpoint: False
    path_base: ''
    filename: ''
