wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1641757415
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 16
      4: 3.7.11
      5: 0.12.9
      8:
      - 3
      - 5
checkpoint:
  desc: null
  value:
    filename: ''
    path_base: ''
    use_checkpoint: false
datasets:
  desc: null
  value:
    configs:
    - dataset:
        augmentation:
          brightness_jitter: 0.2
          contrast_jitter: 0.2
          horizontal_flip: 0.5
          hue_jitter: 0.1
          saturation_jitter: 0.2
        camera: pinhole
        feed_img_size:
        - 512
        - 320
        img_norm: true
        max_depth: 655.35
        min_depth: 0.01
        name: synthia_rand_cityscapes
        num_classes: 19
        path: C:\Users\benba\Documents\University\Masterarbeit\data\SYNTHIA_RAND_CITYSCAPES\RAND_CITYSCAPES
        rgb_frame_offsets:
        - 0
        sequence_dataset: false
        shuffle: true
        split: null
        use_dense_depth: true
        use_self_supervised_depth: false
        use_semantic_gt: true
        use_sparse_depth: false
      eval:
        test:
          gt_depth_available: true
          gt_semantic_available: true
          use_gt_scale: true
        train:
          gt_depth_available: true
          gt_semantic_available: true
          use_gt_scale: true
        use_garg_crop: true
        val:
          gt_depth_available: true
          gt_semantic_available: true
          use_gt_scale: true
      losses:
        loss_names_and_parameters:
        - bce:
            ignore_index: 250
            r: 0.3
          silog_depth:
            weight: 0.85
          snr: None
        loss_names_and_weights:
        - bce: 0.001
          silog_depth: 1
          snr: 0.01
    - dataset:
        augmentation:
          brightness_jitter: 0.2
          contrast_jitter: 0.2
          horizontal_flip: 0.5
          hue_jitter: 0.1
          saturation_jitter: 0.2
        camera: pinhole
        feed_img_size:
        - 512
        - 320
        img_norm: true
        max_depth: 655.35
        min_depth: 0.01
        name: gta5
        num_classes: 19
        path: C:\Users\benba\Documents\University\Masterarbeit\data\gta5
        rgb_frame_offsets:
        - 0
        - -1
        - 1
        sequence_dataset: true
        shuffle: true
        split: null
        use_dense_depth: false
        use_self_supervised_depth: true
        use_semantic_gt: false
        use_sparse_depth: false
      eval:
        test:
          gt_depth_available: false
          gt_semantic_available: true
          use_gt_scale: false
        train:
          gt_depth_available: false
          gt_semantic_available: false
          use_gt_scale: false
        use_garg_crop: true
        val:
          gt_depth_available: false
          gt_semantic_available: true
          use_gt_scale: false
      losses:
        loss_names_and_parameters:
        - reconstruction:
            use_automasking: true
            use_ssim: true
        loss_names_and_weights:
        - reconstruction: 1
    loss_weights:
    - 1
    - 1
    paths_to_configs:
    - C:\Users\benba\Documents\University\Masterarbeit\Depth-Semantic-UDA\cfg\yaml_files\train\guda\synthia.yaml
    - C:\Users\benba\Documents\University\Masterarbeit\Depth-Semantic-UDA\cfg\yaml_files\train\guda\gta5.yaml
device:
  desc: null
  value:
    multiple_gpus: false
    no_cuda: false
experiment_name:
  desc: null
  value: synthia_to_cityscapes
io:
  desc: null
  value:
    log_frequency: 250
    path_save: /home/petek/trained_models/depth_estimation
    save_frequency: 1
model:
  desc: null
  value:
    depth_net:
      nof_scales: 4
      params: {}
    encoder:
      params:
        nof_layers: 101
        weights_init: pretrained
    pose_net:
      input: pairs
      params:
        nof_layers: 18
        weights_init: pretrained
    semantic_net:
      params: {}
    type: guda
train:
  desc: null
  value:
    batch_size: 1
    nof_epochs: 40
    nof_workers: 4
    optimizer:
      learning_rate: 0.0001
      type: Adam
    scheduler:
      gamma: 0.5
      milestones:
      - 30
      step_size: 10
      type: MultiStepLR
val:
  desc: null
  value:
    batch_size: 1
    nof_workers: 4
