experiment_name: 'cityscapes_depth_unsupervised'

model:
    type: 'monodepth2'

    encoder:
        params:
            nof_layers: 50
            weights_init: 'pretrained'

    pose_net:
        input: 'pairs' # 'all'
        params:
            nof_layers: 18
            weights_init: 'pretrained'

datasets:
    paths_to_configs : ['/home/bauschb/Masterthesis/Depth-Semantic-UDA/cfg/yaml_files_server/train/semantic_and_unsupervised_depth/cityscapes_sequence.yaml', # target
                        '/home/bauschb/Masterthesis/Depth-Semantic-UDA/cfg/yaml_files_server/train/semantic_and_unsupervised_depth/cityscapes_semantic.yaml'] # validation dataset
    loss_weights : [1, 0]

train:
    nof_epochs: 40
    batch_size: 1
    nof_workers: 5

    optimizer:
        type: 'Adam'
        learning_rate: 0.0001
    scheduler:
        type: 'MultiStepLR'
        gamma: 0.5
        milestones: [30] # half the learning rate for the last 10 epochs

val:
    batch_size: 1
    nof_workers: 5

checkpoint:
    use_checkpoint: False


device:
    multiple_gpus: True

io:
    path_save: '/work/dlclarge1/bauschb-data/models/depth_unsupervised_cityscapes_cropped'
