experiment_name: 'cityscapes_monodepth2'

model:
    type: 'monodepth2'

    encoder:
        params:
            nof_layers: 101
            weights_init: 'pretrained'

    pose_net:
        input: 'pairs' # 'all'
        params:
            nof_layers: 50
            weights_init: 'pretrained'
            predict_motion_map: True

datasets:
    paths_to_configs : ['/home/bauschb/Masterthesis/Depth-Semantic-UDA/cfg/yaml_files_server/train/depth_unsupervised_with_motion/cityscapes_sequence.yaml', # target
                        '/home/bauschb/Masterthesis/Depth-Semantic-UDA/cfg/yaml_files_server/train/depth_unsupervised_with_motion/cityscapes_semantic.yaml'] # validation dataset
    loss_weights : [1, 0]

train:
    nof_epochs: 120
    batch_size: 1
    nof_workers: 5

    optimizer:
        type: 'Adam'
        learning_rate: 0.0001
    scheduler:
        type: 'MultiStepLR'
        gamma: 0.5
        milestones: [200] # half the learning rate for the last 10 epochs

val:
    batch_size: 1
    nof_workers: 5

checkpoint:
    use_checkpoint: False

device:
    multiple_gpus: True

io:
    path_save: '/work/dlclarge1/bauschb-data/models/cityscapes_monodepth2_with_motion'
