wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    mask/class_labels:
      images_wandb_delimeter_ground_truth:
        key: images_wandb_delimeter_ground_truth
        type: mask/class_labels
        value:
          '0': road
          '1': sidewalk
          '10': sky
          '11': person
          '12': rider
          '13': car
          '14': truck
          '15': bus
          '16': train
          '17': motorcycle
          '18': bicycle
          '2': building
          '250': ignore_index
          '3': wall
          '4': fence
          '5': pole
          '6': traffic_light
          '7': traffic_sign
          '8': vegetation
          '9': terrain
    python_version: 3.8.12
    start_time: 1642441287
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.12
      5: 0.12.9
      8:
      - 5
